title: Tales from the Coppery Isle RPG
description: This will evolve into my own TTRPG as well as site for generating random things for TTRPGs
theme: just-the-docs

url: ttps://YOUR-USERNAME.github.io/YOUR-SITE-NAME

aux_links:
  Template Repository:  https://github.com/YOUR-USERNAME/YOUR-SITE-NAME

plugins:
  - jekyll-default-layout
